shellEmulator: true

trustPolicy: no-downgrade

packages:
  - apps/*
  - packages/*
overrides:
  '@unhead/vue': npm:@unhead/vue@3.0.5
  markdown-it: npm:markdown-exit@1.0.0-beta.6
patchedDependencies:
  markdown-it-table-of-contents: patches/markdown-it-table-of-contents.patch
  vite-ssg: patches/vite-ssg.patch
