packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@dagrejs/dagre': ^1.1.8
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.63
  '@iconify/vue': ^5.0.0
  '@nuxt/ui': ^4.3.0
  '@pinia/colada': ^0.19.1
  '@playwright/test': ^1.56.1
  '@shikijs/markdown-it': ^3.15.0
  '@tailwindcss/typography': ^0.5.19
  '@tsconfig/node-lts': ^22.0.4
  '@types/fs-extra': ^11.0.4
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^25.0.3
  '@unhead/vue': ^2.0.19
  '@unpic/pixels': ^1.3.0
  '@unpic/placeholder': ^0.1.2
  '@vitejs/plugin-vue': ^6.0.2
  '@vue-flow/background': ^1.3.2
  '@vue-flow/core': ^1.47.0
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^13.9.0
  ansis: ^4.2.0
  blurhash: ^2.0.5
  eslint: ^9.39.1
  fs-extra: ^11.3.2
  gray-matter: ^4.0.3
  markdown-it: ^14.1.0
  markdown-it-async: ^2.2.0
  markdown-it-github-alerts: ^1.0.0
  markdown-it-image-figures: ^2.1.1
  markdown-it-link-attributes: ^4.0.1
  markdown-it-table-of-contents: ^1.1.0
  motion-v: ^1.7.4
  ofetch: ^1.5.1
  partysocket: ^1.1.6
  pinia: ^3.0.4
  reka-ui: ^2.6.0
  scule: ^1.3.0
  sharp: ^0.34.5
  shiki: ^3.15.0
  sitemap: ^8.0.2
  tailwind-variants: ^3.2.2
  tailwindcss: ^4.1.18
  taze: ^19.9.0
  typescript: ~5.9.3
  ufo: ^1.6.1
  unhead: ^2.0.19
  unplugin-fonts: ^1.4.0
  unplugin-icons: ^22.5.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-markdown: ^29.2.0
  unplugin-vue-router: ^0.16.2
  vite: npm:rolldown-vite@7.1.20
  vite-ssg: ^28.2.2
  vue: ^3.5.25
  vue-router: 4.6.3
  vue-tsc: ^3.1.4
