packages:
  - apps/*
  - packages/*

catalog:
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.63
  '@nuxt/ui': ^4.3.0
  '@pinia/colada': ^0.19.1
  '@tailwindcss/typography': ^0.5.19
  '@types/node': ^25.0.3
  '@unhead/vue': ^2.0.19
  '@unpic/pixels': ^1.3.0
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^13.9.0
  ansis: ^4.2.0
  markdown-it-github-alerts: ^1.0.0
  motion-v: ^1.7.4
  ofetch: ^1.5.1
  partysocket: ^1.1.6
  pinia: ^3.0.4
  reka-ui: ^2.6.0
  tailwind-variants: ^3.2.2
  tailwindcss: ^4.1.18
  typescript: ~5.9.3
  unplugin-icons: ^22.5.0
  vite: npm:rolldown-vite@7.1.20
  vite-ssg: ^28.2.2
  vue: ^3.5.25
  vue-router: 4.6.3
  vue-tsc: ^3.1.4
